name: saver
description: A professional WhatsApp status saver application.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.4.3
  provider: ^6.0.5
  path_provider: ^2.1.1
  video_player: ^2.7.1
  photo_view: ^0.14.0
  shared_preferences: ^2.2.1
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
